<?=$snippets['header']?>

<main class="page-content">
    <article>
        <div class="wrapper">
            <?=$snippets['secret-toolbar']?>

            <heading class="page-heading">
                <h1 class="breadcrumb">
                    <a href="/secret">Secret area</a> <span class="breadcrumb-separator">/</span> <a href="/secret/todo-list">Todo list</a> <span class="breadcrumb-separator">/</span> New todo
                </h1>
            </heading>

            <section class="form">

                <form action='/secret/todo-list/add' method='POST'>
                    <div class="form-row">
                        <label for="name">Name</label>
                        <input type="text" id="name" name="name" placeholder="Name" class="" />
                    </div>
                    <div class="form-row edit-content">
                        <label for="content">Details</label>
                        <textarea id="details" name="details" placeholder="Write some details if you want..." rows="8"></textarea><br/>
                    </div>
                    <div class="form-row text-right form-bottom-buttom">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                </form>

            </section>
        </div>
    </article>
</main>

<?=$snippets['footer']?>
