<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">
			<?=$snippets['secret-toolbar']?>

			<heading class="page-heading">
				<h1>Secret area</h1>
			</heading>

			<img src="/images/secret-banner.jpg" alt="banner-image" style="width: 100%; border: 2px solid #a2ccdf;"/>

			<p>What should we add here? Any ideas?</p>
			<p>I should make this tool:</p>
			<ol>
				<li>Short/long term goal</li>
				<li>Blog-type log that can be used to report what did I do in order to achieve
					<ol>
						<li>What did I do?</li>
						<li>How long?</li>
						<li>How useful it is?</li>
					</ol>
				</li>
			</ol>

			<p>In the settings:</p>
			<ul>
				<li>Change my description on the front page</li>
				<li>Add/manage slogans</li>
				<li>etc...</li>
			</ul>
		</div>
	</article>
</main>

<?=$snippets['footer']?>
