<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">
			<?=$snippets['secret-toolbar']?>

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/secret">Secret area</a> <span class="breadcrumb-separator">/</span> Todo list
				</h1>
			</heading>

			<p class="text-center"><i>Coming soon...</i></p>

		</div>
	</article>
</main>

<?=$snippets['footer']?>
