<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">
			<?=$snippets['secret-toolbar']?>

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/secret">Secret area</a> <span class="breadcrumb-separator">/</span> Todo list
				</h1>
				<div class="heading-right">
					<a href="/secret/todo-list/create" class="btn btn-primary"><i class="fas fa-edit"></i> New todo</a>
				</div>
			</heading>

			<ul class="resource-list hover-list full-width todo-list">
				<?php foreach (['undone', 'done'] as $status): ?>
				<li class="non-interactable"><h3><?=(ucfirst($status)." (".count($todos->$status).")")?></h3></li>
				<?php if (count($todos->$status) == 0): ?>
				<li class="non-interactable text-center">No todos at the moment.</li>
				<?php else: ?>
				<?php foreach ($todos->$status as $todo): ?>
				<li class="todo--<?=$status?>">
					<div class="resource-list-leftie">
						<input
							type="checkbox"
							name="is_done"
							value="1"
							onChange="updateStatus(event, <?=$todo->id?>, '<?=$todo->name?>', '<?=$todo->done_at?>')"
							<?=(!empty($todo->done_at) ? "checked" : "")?>/>
					</div>
					<?=$todo->name?>
					<span class="pull-right">
						<!--<a
							class="mr-05"
							href="/todo-list/<?=$todo->id?>/edit"
						>
							<i class="fas fa-pen"></i>
						</a>-->

						<a
							href="#"
							onClick="confirmDelete(event, <?=$todo->id?>, '<?=$todo->name?>')"
						>
							<i class="fas fa-trash"></i>
						</a>
					</span>
				</li>
				<?php endforeach; ?>
				<?php endif; ?>
				<?php endforeach; ?>
			</ul>

		</div>
	</article>
</main>

<?=$snippets['footer']?>

<script>
	function confirmDelete(evt, id, name)
	{
		evt.preventDefault();
		let sure = confirm(`Are you sure you want to delete todo: "${name}"?`);

		if (sure) {
			window.location.href = `/secret/todo-list/${id}/delete`;
		}

		return false;
	}

	// TODO: Maybe start using axios?
	function updateStatus(evt, id, title, done_at)
	{
		evt.preventDefault();

		window.location.href = `/secret/todo-list/${id}/update-status`;
	}
</script>