<?php
function makeTitle($active = "")
{
	$title = config('app')['name'];
	if (strlen($active))
		$title .= " &ndash; " . ucfirst($active);
	return $title;
}
?>
<!DOCTYPE html>
<html lang="<?=config('app')['locale']?>">
	<head>
		<meta name="viewport" content= "width=device-width, initial-scale=1.0">
		<title><?=$title ?? makeTitle($active ?? "")?></title>

		<meta name="theme-color" content="#337aaf">
		<meta name="description" content="Homepage of the infamous Spacha. Software engineer, rocket enthusiast and just a nerd in general.">

		<link rel="stylesheet" href="<?=mix("/css/app.css")?>">
		<link rel="icon" href="/images/spacha.svg">
		<script src="<?=mix("/js/app.js")?>"></script>
	</head>
	<body>

		<section class="top-section">
			<header class="main-header">
				<div class="wrapper">
					<div class="main-header--cols hamburgerize">
						
						<div class="ham-header">
							<div class="main-logo--container">
								<a href="/">Spacha<span>.dev</span></a>
							</div>

							<div class="hamburger-container">
								<a class="hamburger" href="#" onClick="toggleHamMenu(event)">
									<i class="fa fa-bars"></i>
								</a>
							</div>
						</div>

						<nav class="main-nav--container">
							<ul class="main-nav ham-menu">
								<li class="<?=(isset($active) && $active == 'home') ?'active':''?>"><a href="/">Home</a></li>
								<li class="<?=(isset($active) && $active == 'users') ?'active':''?>"><a href="/users">Users</a></li>
								<li class="<?=(isset($active) && $active == 'blog') ?'active':''?>"><a href="/blog">Blog</a></li>
								<li class="<?=(isset($active) && $active == 'about') ?'active':''?>"><a href="/about">About</a></li>
							</ul>
						</nav>

					</div>
				</div>
			</header>

			<?=(isset($topSection) && $topSection == true) ? '' : '</section>'?>

			<?php if($auth->loggedIn()): ?>
			<div class="wrapper">
				<div class="loggedin-box">
					<span>
						<i class="fa fa-shield-alt" style="color: #2fb934;"></i>
						Signed in as <?=$auth->user()['name']?>
					</span>
					<span class="loggedin-links">
						<a href="/secret">Secret area</a>
						<a href="/logout">Sign Out</a>
					</span>
				</div>
			</div>
			<?php endif; ?>
