<!DOCTYPE html>
<html>
	<head>
		<title>Alpaca Development</title>

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
		<link rel="stylesheet" href="<?='/css/app.css'?>">
		<script src="/js/app.js"></script>
	</head>
	<body>

		<section class="top-section">
			<header class="main-header">
				<div class="wrapper">
					<div class="main-header--cols">
						
						<div class="main-logo--container">Dummy<span>app</span></div>

						<nav class="main-nav--container">
							<ul class="main-nav">
								<li class="<?=(isset($active) && $active == 'home') ?'active':''?>"><a href="/">Home</a></li>
								<li class="<?=(isset($active) && $active == 'users') ?'active':''?>"><a href="/users">Users</a></li>
								<li class="<?=(isset($active) && $active == 'blog') ?'active':''?>"><a href="/blog">Blog</a></li>
								<li class="<?=(isset($active) && $active == 'about') ?'active':''?>"><a href="/about">About</a></li>
							</ul>
						</nav>

					</div>
				</div>
			</header>
			<?=(isset($topSection) && $topSection == true) ? '' : '</section>'?>
