<div class="secret-toolbar">
	<a href="/secret/logs" class="toolbar-tool">
		<div class="tool-icon"><i class="fas fa-list-alt"></i></div>
		View logs
	</a>

	<a href="/secret/todo-list" class="toolbar-tool">
		<div class="tool-icon"><i class="fas fa-clipboard-check"></i></div>
		Todo list
	</a>

	<a href="/secret/settings" class="toolbar-tool">
		<div class="tool-icon"><i class="fas fa-tools"></i></div>
		Settings
	</a>
</div>