
<div class="secret-toolbar">
    <a href="/secret/pages" class="toolbar-tool<?=$activeClass('pages', ' ')?>">
        <div class="tool-icon"><i class="fas fa-file-alt"></i></div>
        Pages
    </a>

    <a href="/secret/todo-list" class="toolbar-tool<?=$activeClass('todo-list', ' ')?>">
        <div class="tool-icon"><i class="fas fa-clipboard-check"></i></div>
        Todo list
    </a>

    <a href="/secret/logs" class="toolbar-tool<?=$activeClass('logs', ' ')?>">
        <div class="tool-icon"><i class="fas fa-list-alt"></i></div>
        View logs
    </a>

    <a href="/secret/settings" class="toolbar-tool<?=$activeClass('settings', ' ')?>">
        <div class="tool-icon"><i class="fas fa-tools"></i></div>
        Settings
    </a>
</div>