
<div class="secret-toolbar">
	<a href="/secret/logs" class="toolbar-tool<?=(isset($active) && $active == 'logs') ?' active':''?>">
		<div class="tool-icon"><i class="fas fa-list-alt"></i></div>
		View logs
	</a>

	<a href="/secret/todo-list" class="toolbar-tool<?=(isset($active) && $active == 'todo-list') ?' active':''?>">
		<div class="tool-icon"><i class="fas fa-clipboard-check"></i></div>
		Todo list
	</a>

	<a href="/secret/settings" class="toolbar-tool<?=(isset($active) && $active == 'settings') ?' active':''?>">
		<div class="tool-icon"><i class="fas fa-tools"></i></div>
		Settings
	</a>
</div>