<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/">Alpaca</a> <span class="breadcrumb-separator">/</span> Register
				</h1>
			</heading>


			<section class="form">
				<form action='/auth/register' method='POST'>
					<div class="form-inline form-narrow">

						<div class="form-left"><label for="email">Email</label></div>
						<div class="form-right"><input type="email" id="email" name="email" placeholder="Email" class="full-width" /></div>

						<div class="form-left"><label for="password">Password</label></div>
						<div class="form-right"><input type="password" id="password" name="password" placeholder="Password" class="full-width" /></div>

						<div class="form-left"><label for="password">Repeat Password</label></div>
						<div class="form-right"><input type="password" id="password_repeat" name="password_repeat" placeholder="Repeat password" class="full-width" /></div>

						<div class="form-bottom form-bottom-buttom">
							<!--<p class="text-muted">Don't have an account yet? <a href="/register">Register now.</a></p>-->
							<p>Don't have en account yet? Boohoo.</p>
							<button class="btn btn-primary" type="submit">Register</button>
						</div>

					</div>
				</form>
			</section>
		</div>
	</article>
</main>

<?=$snippets['footer']?>
