<?=$snippets['header']?>

<article class="main">
	<div class="wrapper">

		<h1><span>Create a user</span></h1>

		<form action='/users/add' method='POST'>
			<input type='text' name='name' placeholder='Name' />
			<input type='number' name='age' placeholder='Age' />
			<input type='text' name='phone' placeholder='Phone' />
			<button type='submit'>Add</button>
		</form>

	</div>
</article>

<?=$snippets['footer']?>
