<?=$snippets['header']?>

<article class="main">
	<div class="wrapper">

		<h1><span>Create a user</span></h1>

		<div class="center">	
			<div class="auth-box">

				<form action='/users/add' method='POST'>
					<input type='text' name='name' placeholder='Name' /><br/>
					<input type='number' name='age' placeholder='Age' /><br/>
					<input type='text' name='phone' placeholder='Phone' /><br/>
					<button type='submit'>Add</button>
				</form>

			</div>
		</div>

	</div>
</article>

<?=$snippets['footer']?>
