<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/users">Users</a> <span class="breadcrumb-separator">/</span> New user
				</h1>
			</heading>


			<section class="form">

				<form action='/users/add' method='POST'>
					<table class="table" style="width: 80%;">
						<tbody>
							<tr>
								<td><label for="name">Full name</label></td>
								<td><input type="text" id="name" name="name" placeholder="Name" class="full-width" /></td>
							</tr>
							<tr>
								<td><label for="phone">Phone</label></td>
								<td><input type="text" id="phone" name="phone" placeholder="Phone" class="full-width" /></td>
							</tr>
							<tr>
								<td><label for="age">Age</label></td>
								<td><input type="number" id="age" name="age" placeholder="Age" min="0" max="200" style="width: 100px;" /></td>
							</tr>
							<tr>
								<td></td>
								<td class="text-right">
									<button class="btn btn-primary" type="submit">Add</button>
								</td>
							</tr>
						</tbody>
					</table>
				</form>
			</section>
		</div>
	</article>
</main>

<?=$snippets['footer']?>
