<?=$snippets['header']?>


<article class="main">
	<div class="wrapper">
		<h1><span>Users</span></h1>

		<p><a href='/users/create'>+ Add user</a></p>

		<ul class="user-list hover-list">
			<?php foreach($users as $user): ?>
				<li>
					<a href='/users/<?=$user->id?>'><?=$user->name?></a>
					<a class="pull-right" href="/users/<?=$user->id?>/delete">X</a>
				</li>
			<?php endforeach; ?>
		</ul>

	</div>
</article>

<?=$snippets['footer']?>
