<?=$snippets['header']?>

<main>
	<article>
		<section class="intro">
			<div class="wrapper">
				
				<h1>Welcome to my Life!</h1>
				<h2>Alpaca is light but scalable PHP framework for those who like Rapid and Eloquent Web Development.</h2>
				<h3>
					<a href="https://spacha.github.io/Alpaca" target="blank">https://spacha.github.io/Alpaca</a>
				</h3>

			</div>
		</section>
	</article>
</main>

<?=$snippets['footer']?>
