<?=$snippets['header']?>

<?php
function calcAge()
{
	$years = date('Y')-1996;
	$notYet = date('m') < 12 || date('d') < 10;

	return $years - (int)$notYet;
}
function dateToDay($date)
{
	return date_format(date_create($date), 'd.m.Y');
}
?>

	<section class="intro">
		<div class="wrapper">
			
			<h1 class="slogan before-fading"><?=$slogan?></h1>
			<h2>Alpaca is light but scalable PHP framework for those who like Rapid and Eloquent Web Development.</h2>
			<h3>
				<a href="https://spacha.github.io/Alpaca" target="blank">https://spacha.github.io/Alpaca</a>
			</h3>

		</div>
	</section>
</section>

<main class="page-content">
	<article>
		<section>
			<div class="wrapper">
				<div class="personal-cols">
					<div class="left-col">
						<div class="image-circle">
							<img src="/images/bare-butt.png" alt="my-face" />
						</div>
					</div>
					<div class="right-col">
						<h3>Miika Sikala, <?=calcAge()?></h3>
						<p>I'm a Finnish guy who likes rockets, programming, electonics and so many other things. Currently I'm studying in Oulu University and work as a freelance web developer.</p>
						<pre><code class="language-css">p { color: red }</code></pre>
						<p><a href="/about">Still interested?</a></p>
					</div>
				</div>
			</div>
		</section>

		<section>
			<div class="wrapper">
				<div class="blog-highlights">
					<h2 class="bottom-border">Fresh from my blog</h2>
					<ul>
						<?php if(!isset($recentPosts) || count($recentPosts) == 0): ?>
						<div class="empty-list">
							Looks pretty empty to me <i class="far fa-grin-beam"></i>
						</div>
						<?php else: ?>
						<?php foreach($recentPosts as $post): ?>
						<li>
							<h3>
								<div class="blog-highlights--date">
									<?=dateToDay($post->created_at)?>
								</div>
								<div>
									<a href="/blog/<?=$post->id?>"><?=$post->title?></a>
									<!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
									tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>-->
								</div>
							</h3>
						</li>
						<?php endforeach; ?>
						<?php endif ?>
					</ul>
				</div>
			</div>
		</section>

		<section class="social-links-section">
			<div class="wrapper">
				<h2 class="text-center">My Social Media</h2>

				<div class="social-links">
					<a href="https://github.com/Spacha" target="_blank" rel="noopener" class="social-github">
						<i class="fab fa-github"></i> Github
					</a>

					<a href="https://linkedin.com/in/miika-sikala" target="_blank" rel="noopener" class="social-linkedin">
						<i class="fab fa-linkedin"></i> Linkedin
					</a>

					<a href="https://steamcommunity.com/id/spacha" target="_blank" rel="noopener" class="social-steam">
						<i class="fab fa-steam"></i> Steam
					</a>
				</div>
			</div>
		</section>
	</article>
</main>

<?=$snippets['footer']?>
