<?=$snippets['header']?>

<article class="main">
	<div class="wrapper">

		<h1><span>Home</span></h1>
		<p>This is home. Home sweet home!</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam accusamus officiis est, recusandae nam, illum aliquid fugit consequuntur labore pariatur. Numquam aperiam quidem voluptates optio perferendis id blanditiis assumenda corporis?</p>

	</div>
</article>

<?=$snippets['footer']?>
