<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/secret/pages"><?=$page->header?></a> <span class="breadcrumb-separator">/</span> Edit page
				</h1>
			</heading>

			<section class="form">
				<form action='/secret/pages/<?=$page->id?>/update' method='POST'>
					<div class="form-row">
						<label for="title">Header</label>
						<input type="text" id="header" name="header" placeholder="Header" class="" value="<?=$page->header?>" />
					</div>
					<div class="form-row">
						<label for="title">Title</label>
						<input type="text" id="title" name="title" placeholder="Title" class="" value="<?=$page->title?>" />
					</div>
					<div class="form-row">
						<label for="title">Url</label>
						<input type="text" id="title" name="title" placeholder="Title" class="" value="<?=$page->url?>" />
					</div>
					<div class="form-row">
						<label for="content">Content</label>
						<textarea id="content" name="content" placeholder="Write some content..." style="min-height: 20rem;"><?=$page->content?></textarea>
					</div>
					<div class="form-row form-row-inline">
						<label for="is_public" style="width: 7.5rem;">Set public</label>
						<input type="checkbox" id="is_public" name="is_public" value="1" class="" <?=($page->is_public ? "checked" : "")?> onChange="highlightWarning(event)"/>
					</div>
					<div class="form-row-inline text-right form-bottom-buttom">
						<button class="btn btn-primary" type="submit">Save</button>
					</div>
				</form>

			</section>
		</div>
	</article>
</main>

<?=$snippets['footer']?>
