<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">
			<?=$snippets['secret-toolbar']?>

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/secret/pages">Pages</a> <span class="breadcrumb-separator">/</span> <?=$page->header?>
				</h1>
			</heading>
			<div class="post-tools">
				<div>

					<?php if($page->is_public && strlen($page->url ?? '') > 0): ?>
					<a href="/<?=$page->url?>" target="_blank">
						<i class="fas fa-eye"></i> View live
					</a>
					<?php else: /* Cannot be viewed */ ?>
					<a class="disabled" aria-current="page" title="Page has no url or is not public.">
						<i class="fas fa-eye"></i> View live
					</a>
					<?php endif ?>
				</div>
				<div><a href="/secret/pages/<?=$page->id?>/edit"><i class="fas fa-edit"></i> Edit</a></div>
				<div>
					<a href="/secret/pages/<?=$page->id?>/delete" onClick="confirmDelete(event, <?=$page->id?>, '<?=$page->header?>')">
						<i class="fas fa-trash"></i> Delete
					</a>
				</div>
			</div>

			<div class="blog--post">
				<?=$page->contentHtml?>

				<p class="text-center mt-2"><a href="/secret/pages"><i class="far fa-hand-point-left"></i> Return</a></p>
			</div>
		</div>
	</article>
</main>

<?=$snippets['footer']?>

<script>
	function confirmDelete(evt, id, title)
	{
		evt.preventDefault();
		let sure = confirm(`Are you sure you want to delete post: "${title}"?`);

		if (sure) {
			window.location.href = `/secret/pages/${id}/delete`;
		}

		return false;
	}
</script>
