<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">

			<heading class="page-heading">
				<h1><?=$page->header?></h1>
			</heading>
			<div class="post-tools">
				<div>
					<a href="/<?=$page->url?>" target="_blank">
						<i class="fa fa-shield-alt"></i> View in secret
					</a>
				</div>
				<div><a href="/secret/pages/<?=$page->id?>/edit"><i class="fas fa-edit"></i> Edit</a></div>
				<div>
					<a href="/secret/pages/<?=$page->id?>/delete" onClick="confirmDelete(event, <?=$page->id?>, '<?=$page->header?>')">
						<i class="fas fa-trash"></i> Delete
					</a>
				</div>
			</div>

			<div class="blog--post">
				<?=$page->contentHtml?>

				<p class="text-center mt-2"><a href="/blog"><i class="far fa-hand-point-left"></i> Return</a></p>
			</div>
		</div>
	</article>
</main>

<?=$snippets['footer']?>

<script>
	function confirmDelete(evt, id, title)
	{
		evt.preventDefault();
		let sure = confirm(`Are you sure you want to delete post: "${title}"?`);

		if (sure) {
			window.location.href = `/secret/pages/${id}/delete`;
		}

		return false;
	}
</script>
