<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">
			<?=$snippets['secret-toolbar']?>

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/secret">Secret area</a> <span class="breadcrumb-separator">/</span> <a href="/secret/logs">Logs</a> <span class="breadcrumb-separator">/</span> Error log
				</h1>
			</heading>

			<div class="mb-1">
				<a href="#" class="btn btn-secondary btn-fit" onClick="expandLog(event)">
					<i class="fas fa-arrows-alt-h"></i>
					<span id="expand-btn-text">Expand</span>
				</a>
			</div>

			<div class="log-textarea-container" id="log-container">
				<div>
					<textarea class="log-textarea" readonly><?=$errorLog?></textarea>
				</div>
			</div>

		</div>
	</article>
</main>

<?=$snippets['footer']?>

<script>
	function expandLog(evt)
	{
		evt.preventDefault();
		let container = document.getElementById('log-container');
		let btnText = document.getElementById('expand-btn-text');

		if (container.classList.contains('expanded')) {
			// collapse...
			container.classList.remove('expanded');
			btnText.innerHTML = 'Expand';
		} else {
			// expand...
			container.classList.add('expanded');
			btnText.innerHTML = 'Collapse';
		}
	}
</script>