<?=$snippets['header']?>

<main class="page-content">
    <article>
        <div class="wrapper">
            <?=$snippets['secret-toolbar']?>

            <heading class="page-heading">
                <h1 class="breadcrumb">
                    <a href="/secret">Secret area</a> <span class="breadcrumb-separator">/</span> Logs
                </h1>
            </heading>

            <div class="secret-toolbar">
                <a href="/secret/logs/error-log" class="toolbar-tool">
                    <i class="fas fa-exclamation-triangle"></i> Error log
                </a>

                <a href="/secret/logs/activity-log" class="toolbar-tool">
                    <i class="fas fa-history"></i> Activity log
                </a>
            </div>

        </div>
    </article>
</main>

<?=$snippets['footer']?>
