<?=$snippets['header']?>

<article class="main">
	<div class="wrapper">

		<h1><span>Write a post</span></h1>

		<div class="wide-input">

			<form action="/blog/add" method="POST">
				<input type="text" name="title" placeholder="Title" /><br/>
				<textarea name="content" placeholder="Write some content..." rows="8"></textarea><br/>
				<button type="submit">Add</button>
			</form>

		</div>
	</div>
</article>

<?=$snippets['footer']?>
