<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/blog">Blog</a> <span class="breadcrumb-separator">/</span> Edit post
				</h1>
			</heading>

			<section class="form">

				<form action='/blog/<?=$post->id?>/update' method='POST'>
					<div class="form-row">
						<label for="title">Title</label>
						<input type="text" id="title" name="title" placeholder="Title" class="" value="<?=$post->title?>" />
					</div>
					<div class="form-row">
						<label for="content">Content</label>
						<textarea id="content" name="content" placeholder="Write some content..." style="min-height: 20rem;" onKeyDown="captureTab(event)"><?=$post->content?></textarea>
						<span class="form-note">Markdown help: <a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">https://daringfireball.net/projects/markdown/syntax</a></span>
					</div>
					<div class="form-row form-row-inline">
						<label for="category_id" style="width: 7.5rem;">Category</label>
						<select id="category_id">
							<?php if(count($categories) > 0): ?>
							<?php foreach ($categories as $category): ?>
							<option value="<?=$category->id?>">
								<?=$category->title?>
							</option>
							<?php endforeach; ?>
							<?php else: ?>
								<option value="0" disabled selected>No categories...</option>
							<?php endif; ?>
						</select>
					</div>
					<div class="form-row form-row-inline">
						<label for="is_public" style="width: 7.5rem;">Set public</label>
						<input type="checkbox" id="is_public" name="is_public" value="1" class="" <?=($post->is_public ? "checked" : "")?> />
					</div>
					<div class="form-row-inline text-right form-bottom-buttom">
						<button class="btn btn-primary" type="submit">Save</button>
					</div>
				</form>
			</section>
		</div>
	</article>
</main>

<?=$snippets['footer']?>
