<?=$snippets['header']?>

<article class="main">
	<div class="wrapper">

		<heading class="clearfix page-heading">
			<h1>Blog</h1>
			<div class="heading-right">
				<a href="/blog/create" class="btn btn-primary"><i class="fas fa-edit"></i> New post</a>
			</div>
		</heading>

		<p>Here I write about things I find interesting. Head right in!</p>
		<p>– Spacha</p>

		<?php foreach ($posts as $post): ?>
		<li><a href="blog/<?=$post->id?>"><?=$post->title?></a>
		<?php endforeach ?>

	</div>
</article>

<?=$snippets['footer']?>
