<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">

			<heading class="clearfix page-heading">
				<h1>Blog</h1>
				<?php if($auth->loggedIn()): ?>
				<div class="heading-right">
					<a href="/blog/create" class="btn btn-primary"><i class="fas fa-edit"></i> New post</a>
				</div>
				<?php endif; ?>
			</heading>

			<p>Here I write about things I find interesting. Mostly I write for myself. For some reason it's fun to write things down; how it's been and what I have been up to. Sometimes I tend to go too much into details, but I think it's fine! It's so fun to come back years later and read my old posts. It makes me feel like it happened yesterday, yet like I would be reading somebody else's blog!</p>

			<p>Without further ado, head right in and have fun.</p>

			<ul class="resource-list hover-list full-width">
				<?php if (count($posts) == 0): ?>
				<li class="non-interactable text-center">No posts at the moment.</li>
				<?php endif; ?>
				<?php foreach ($posts as $post): ?>
					<li>
						<?php if($auth->loggedIn()): ?>
							<div class="resource-list-leftie">
								<input
									type="checkbox"
									name="is_public"
									value="1"
									onChange="updatePublicity(event, <?=$post->id?>, '<?=addslashes($post->title)?>', <?=$post->is_public?>)"
									<?=($post->is_public ? "checked" : "")?>/>
							</div>
						<?php endif; ?>
						<a href='/blog/<?=$post->id?>'><?=$post->title?></a>
						<?php if($auth->loggedIn()): ?>
						<span class="pull-right">
							<a
								class="mr-05"
								href="/blog/<?=$post->id?>/edit"
							>
								<i class="fas fa-pen"></i>
							</a>

							<a
								href="/blog/<?=$post->id?>/delete"
								onClick="confirmDelete(event, <?=$post->id?>, '<?=$post->title?>')"
							>
								<i class="fas fa-trash"></i>
							</a>
						</span>
						<?php endif; ?>
					</li>
				<?php endforeach; ?>
			</ul>

		</div>
	</article>
</main>

<?=$snippets['footer']?>

<?php if($auth->loggedIn()): ?>
<script>
	function confirmDelete(evt, id, title)
	{
		evt.preventDefault();
		let sure = confirm(`Are you sure you want to delete post: "${title}"?`);

		if (sure) {
			window.location.href = `/blog/${id}/delete`;
		}

		return false;
	}

	// TODO: Maybe start using axios?
	function updatePublicity(evt, id, title, is_public)
	{
		evt.preventDefault();

		var sure = true;
		if (!is_public) {
			sure = confirm(`Are you sure you want to publish post: "${title}"?`);
		}

		if (sure) {
			window.location.href = `/blog/${id}/update-publicity`;
		}
	}
</script>
<?php endif; ?>