<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/blog">Blog</a> <span class="breadcrumb-separator">/</span> <?=$post->title?>
				</h1>
			</heading>
			<p class="blog--author"><span>by <?=$post->author?> <?=$post->created_at?></span></p>

			<div class="blog--post">
				<?=nl2br($post->content)?>

				<p class="text-center mt-2"><a href="/blog"><i class="far fa-hand-point-left"></i> Return</a></p>
			</div>
		</div>
	</article>
</main>

<?=$snippets['footer']?>
