<?=$snippets['header']?>

<main class="page-content">
	<article>
		<div class="wrapper">

			<heading class="page-heading">
				<h1 class="breadcrumb">
					<a href="/blog">Blog</a> <span class="breadcrumb-separator">/</span> <?=$post->title?>
				</h1>
			</heading>
			<p><span>by <?=$post->author?> <?=$post->created_at?></span></p>

			<?=$post->content?>
			
		</div>
	</article>
</main>

<?=$snippets['footer']?>
